// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqMJOcCe2WBxra8wLZBfZb6dC109iZ_k',
    appId: '1:141423859663:web:56996264ac7fe7f45224ba',
    messagingSenderId: '141423859663',
    projectId: 'codingmindsproject',
    authDomain: 'codingmindsproject.firebaseapp.com',
    storageBucket: 'codingmindsproject.firebasestorage.app',
    measurementId: 'G-R33NPVBBYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAeuhoLyVFdZ6S4QIk_7Oe5DTZ_96UhX0',
    appId: '1:141423859663:android:c43bcebeb9521e155224ba',
    messagingSenderId: '141423859663',
    projectId: 'codingmindsproject',
    storageBucket: 'codingmindsproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOivlY9tBZvxnG98D-ipGOwbYTvtENl30',
    appId: '1:141423859663:ios:ecce3816b11011b25224ba',
    messagingSenderId: '141423859663',
    projectId: 'codingmindsproject',
    storageBucket: 'codingmindsproject.firebasestorage.app',
    iosClientId: '141423859663-sb5a88ed95f5ps9867o677rf8cs6b2oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOivlY9tBZvxnG98D-ipGOwbYTvtENl30',
    appId: '1:141423859663:ios:ecce3816b11011b25224ba',
    messagingSenderId: '141423859663',
    projectId: 'codingmindsproject',
    storageBucket: 'codingmindsproject.firebasestorage.app',
    iosClientId: '141423859663-sb5a88ed95f5ps9867o677rf8cs6b2oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByqMJOcCe2WBxra8wLZBfZb6dC109iZ_k',
    appId: '1:141423859663:web:6b3b14649e7236af5224ba',
    messagingSenderId: '141423859663',
    projectId: 'codingmindsproject',
    authDomain: 'codingmindsproject.firebaseapp.com',
    storageBucket: 'codingmindsproject.firebasestorage.app',
    measurementId: 'G-Q837LK95R4',
  );

}